apiVersion: v1
kind: Service
metadata:
  name: treasurebook-mongo-service
spec:
  type: ClusterIP  # Expose MongoDB internally within the Kubernetes cluster
  selector:
    app: treasurebook-mongo
  ports:
  - protocol: TCP
    port: 27017        # MongoDB default port
    targetPort: 27017  # MongoDB container port
